spring:
  application:
      name: app-service
  datasource:
    url: jdbc:db2://dashdb-txn-sbox-yp-dal09-11.services.dal.bluemix.net:50000/BLUDB:currentSchema=LFL34414;
    username: lfl34414
    password: s0l78pp-zvjsh68m
    driver-class-name: com.ibm.db2.jcc.DB2Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
